# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "categories_events", :id => false, :force => true do |t|
    t.column "event_id",    :integer
    t.column "category_id", :integer
  end

  create_table "events", :force => true do |t|
    t.column "title",       :string
    t.column "location",    :string
    t.column "occurs_on",   :date
    t.column "url",         :string
    t.column "description", :text
    t.column "user_id",     :integer
  end

  create_table "registrations", :force => true do |t|
    t.column "user_id",    :integer
    t.column "event_id",   :integer
    t.column "note",       :text
    t.column "created_at", :datetime
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "taggable_id",   :integer
    t.column "tag_id",        :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",           :string
    t.column "email",           :string
    t.column "hashed_password", :string
  end

end
